GEMINI_API_KEY = "AQ.Ab8RN6JIKEHV8HUMvJ1rzGUr3sFpWvffgkn72rupj22YrZpixA"

SUPABASE_URL = "https://ymdfkhmehplucjavjngu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltZGZraG1laHBsdWNqYXZqbmd1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4OTI3OTI3MCwiZXhwIjoyMTA0ODU1MjcwfQ.-9kk7jnYQuoCaXc5BUra-Et4AzSiyZ6LgunYMwY0afc"

